### ISSUE TITLE
OCaml's int is not large enough to hold errno values on all platforms (e.g. hurd-i386)

### ISSUE THREAD

**Issue by yallop** [dsheets/ocaml-unix-errno#11]
See https://github.com/ocamllabs/ocaml-ctypes/issues/409

**Comment by dsheets** [comment]
How very... special. Would an `int32` work? `nativeint`? This is annoying...

**Comment by yallop** [comment]
Ctypes `HEAD` has a [new `sint` type](https://github.com/ocamllabs/ocaml-ctypes/pull/411) that matches the native integer type of the platform.

Using `sint` means depending on ctypes, unfortunately.  However, since `errno` is a C type, perhaps that's not entirely unreasonable.
